module Flecs
  class Iter < FFI::Struct
    layout(
      world: ?*ecs_world_t,
      real_world: ?*ecs_world_t,
      entities: [*c]ecs_entity_t,
      ptrs: [*c]?*anyopaque,
      sizes: [*c]ecs_size_t,
      table: ?*ecs_table_t,
      type: ecs_type_t,
      other_table: ?*ecs_table_t,
      ids: [*c]ecs_id_t,
      variables: [*c]ecs_var_t,
      columns: [*c]i32,
      subjects: [*c]ecs_entity_t,
      match_indices: [*c]i32,
      references: [*c]ecs_ref_t,
      constrained_vars: ecs_flags64_t,
      system: ecs_entity_t,
      event: ecs_entity_t,
      event_id: ecs_id_t,
      self: ecs_entity_t,
      terms: [*c]ecs_term_t,
      table_count: i32,
      term_count: i32,
      term_index: i32,
      variable_count: i32,
      variable_names: [*c][*c]u8,
      param: ?*anyopaque,
      ctx: ?*anyopaque,
      binding_ctx: ?*anyopaque,
      delta_time: f32,
      delta_system_time: f32,
      frame_offset: i32,
      offset: i32,
      count: i32,
      instance_count: i32,
      flags: ecs_flags32_t,
      interrupted_by: ecs_entity_t,
      priv: ecs_iter_private_t,
      next: ecs_iter_next_action_t,
      callback: ecs_iter_action_t,
      fini: ecs_iter_fini_action_t,
      chain_it: [*c]ecs_iter_t,
    )
  end
end
