inherit_gem:
  standard: config/base.yml

require:
  - standard
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
    - "**/*_spec.rb"

# It's common to have one-line methods for component helpers
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
